[simulation]
sim_epoch   = "2025-01-01T00:00:00"
sim_time    = 1577880000 # seconds
dt          = 86400.0 # seconds
integrator  = "IAS15"
kernel_path = "/home/matej/Desktop/dasst/de440.bsp"
in_frame    = "HCRS"
out_frame   = "HCRS"
tqdm        = true
seed        = 1234

[simulation.reboundx]

  # List of extra forces (ReboundX)
  [[simulation.reboundx.forces]]
  name = "radiation_forces"

  [simulation.reboundx.forces.params]
  c = 299792458.0   # speed of light [m/s]

  [[simulation.reboundx.particle_params]]
  pindex = -1

  [simulation.reboundx.particle_params.params]
  beta = 5e-2
